# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsTaggy < Formula
  desc "AWS Taggy is a CLI tool that ensures tag compliance for AWS resources, enhancing efficiency and supporting your FinOps goals."
  homepage "https://github.com/Excoriate/aws-taggy"
  version "1.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Excoriate/aws-taggy/releases/download/v1.4.0/aws-taggy_1.4.0_darwin_amd64.tar.gz"
      sha256 "38941f8a217ede3a4734c85a6cbe44ad0c76dceffd0d181e9b6c33d389e5b8e5"

      def install
        bin.install "aws-taggy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Excoriate/aws-taggy/releases/download/v1.4.0/aws-taggy_1.4.0_darwin_arm64.tar.gz"
      sha256 "b494d02465d9649debe41386aa5aa9f955f10f28c284921dff8248c028150530"

      def install
        bin.install "aws-taggy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Excoriate/aws-taggy/releases/download/v1.4.0/aws-taggy_1.4.0_linux_amd64.tar.gz"
        sha256 "1c83ad4a28597f48e838302761a3cb9aec581a4293e2de47b49327ea7f5836fe"

        def install
          bin.install "aws-taggy"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Excoriate/aws-taggy/releases/download/v1.4.0/aws-taggy_1.4.0_linux_arm.tar.gz"
        sha256 "aee20eee5d33e73280d50e0b1f87997434d3536eb6f5ee073248d84731dd75b0"

        def install
          bin.install "aws-taggy"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Excoriate/aws-taggy/releases/download/v1.4.0/aws-taggy_1.4.0_linux_arm64.tar.gz"
        sha256 "854d6a4ce4d768d8d4e1f0db36edff03430dffe6b2243fed23382ad74f2a92a3"

        def install
          bin.install "aws-taggy"
        end
      end
    end
  end
end
