# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsTaggy < Formula
  desc "AWS Taggy is a CLI tool that ensures tag compliance for AWS resources, enhancing efficiency and supporting your FinOps goals."
  homepage "https://github.com/Excoriate/aws-taggy"
  version "1.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Excoriate/aws-taggy/releases/download/v1.5.0/aws-taggy_1.5.0_darwin_amd64.tar.gz"
      sha256 "0223f6dd4905d4886413ee0247287e90f3db5cf6e8de551c7ad362b47a7755a7"

      def install
        bin.install "aws-taggy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Excoriate/aws-taggy/releases/download/v1.5.0/aws-taggy_1.5.0_darwin_arm64.tar.gz"
      sha256 "724728cb0119f1b29a3330a198663033be61c84fccc83a341aec0bbfea99c1d8"

      def install
        bin.install "aws-taggy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Excoriate/aws-taggy/releases/download/v1.5.0/aws-taggy_1.5.0_linux_amd64.tar.gz"
        sha256 "6303240a106a96e570436c8bf956dc60ce87f42e0c227fb34459c4569a140307"

        def install
          bin.install "aws-taggy"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Excoriate/aws-taggy/releases/download/v1.5.0/aws-taggy_1.5.0_linux_arm.tar.gz"
        sha256 "191d97d208b06c5af138b0cef4b05e8f90a0414b5115c95fe7ce9aa17f489ac3"

        def install
          bin.install "aws-taggy"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Excoriate/aws-taggy/releases/download/v1.5.0/aws-taggy_1.5.0_linux_arm64.tar.gz"
        sha256 "008ecb9f2d885aae960c11cdf99fff112301e0dacc312a323cb76706bda90343"

        def install
          bin.install "aws-taggy"
        end
      end
    end
  end
end
