# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DaggerPythonEcs < Formula
  desc "A CLI tool, framework, portable pipeline... anything you want it to be, for automating stuffs."
  homepage "https://github.com/Excoriate/dagger-python-ecs"
  version "0.4.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Excoriate/dagger-python-ecs/releases/download/v0.4.1/dagger-python-ecs_0.4.1_darwin_arm64.tar.gz"
      sha256 "5e3e7ea170591cf27707a04f92c90d21e882daa9a83a07e4f8ec2ed386e8bcac"

      def install
        bin.install "dagger-python-ecs"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Excoriate/dagger-python-ecs/releases/download/v0.4.1/dagger-python-ecs_0.4.1_darwin_amd64.tar.gz"
      sha256 "e40f3f769c3e872b65d367c99cbd7d8cfc7ac7ad587c573364fe67d32f4d16bb"

      def install
        bin.install "dagger-python-ecs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Excoriate/dagger-python-ecs/releases/download/v0.4.1/dagger-python-ecs_0.4.1_linux_armv6.tar.gz"
      sha256 "f9369857928faf90a403a5ab55fc884c83fa9321b4604d5979de40fce2829341"

      def install
        bin.install "dagger-python-ecs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Excoriate/dagger-python-ecs/releases/download/v0.4.1/dagger-python-ecs_0.4.1_linux_arm64.tar.gz"
      sha256 "2e975475074faded57a95163c2570d2ddfba7c07f2b4ebb8de3f2cb540ab7bdc"

      def install
        bin.install "dagger-python-ecs"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Excoriate/dagger-python-ecs/releases/download/v0.4.1/dagger-python-ecs_0.4.1_linux_amd64.tar.gz"
      sha256 "46c1d4497dff3afa408e9c42ca5aa8394b16a3ee2fe603f16dceefc2f35b7c37"

      def install
        bin.install "dagger-python-ecs"
      end
    end
  end
end
