# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glonner < Formula
  desc "A CLI tool for devour repositories within a given GitHub organization."
  homepage "https://github.com/Excoriate/glonner-cli"
  version "0.2.15"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Excoriate/glonner-cli/releases/download/0.2.15/glonner_0.2.15_darwin_arm64.tar.gz"
      sha256 "b7cfa4e8e92c5ac30ca004d7814b5e971f67b771de3153569b2106f3471175ea"

      def install
        bin.install "glonner"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Excoriate/glonner-cli/releases/download/0.2.15/glonner_0.2.15_darwin_amd64.tar.gz"
      sha256 "9ebc077e500d958ab5defbe3dd4ac6abcf0918af70710d6c3dcef40d1edaf433"

      def install
        bin.install "glonner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Excoriate/glonner-cli/releases/download/0.2.15/glonner_0.2.15_linux_armv6.tar.gz"
      sha256 "48d4a7bb61d5e3bf0813c3ba2635403433ba0ddb3c47ffcdf1b062615767110a"

      def install
        bin.install "glonner"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Excoriate/glonner-cli/releases/download/0.2.15/glonner_0.2.15_linux_arm64.tar.gz"
      sha256 "14fafec0069d3a0cf55258fb4f11daa64d2010543ed3d5b17853be92762ea1b7"

      def install
        bin.install "glonner"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Excoriate/glonner-cli/releases/download/0.2.15/glonner_0.2.15_linux_amd64.tar.gz"
      sha256 "b2e09e096cb8a94ffa6cdc82b6922f4ceb0fca02231b8744e0ce8d59a3c7eead"

      def install
        bin.install "glonner"
      end
    end
  end
end
