# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glonner < Formula
  desc "A CLI tool for devour repositories within a given GitHub organization."
  homepage "https://github.com/Excoriate/glonner-cli"
  version "0.6.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Excoriate/glonner-cli/releases/download/0.6.0/glonner_0.6.0_darwin_amd64.tar.gz"
      sha256 "fe87c88bd3fd2e4396d93225efd01eb673aaa95cac2309287813df3ded2e8d2f"

      def install
        bin.install "glonner"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Excoriate/glonner-cli/releases/download/0.6.0/glonner_0.6.0_darwin_arm64.tar.gz"
      sha256 "b689bfa70a18d61589369aa881e95464e10b32de9150f5d5ae5bdce0b15b775f"

      def install
        bin.install "glonner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Excoriate/glonner-cli/releases/download/0.6.0/glonner_0.6.0_linux_armv6.tar.gz"
      sha256 "e10a16bd0ccb51bf4725b0924f1ff8480f11e3b2d09363d57ea56d06498c1b3f"

      def install
        bin.install "glonner"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Excoriate/glonner-cli/releases/download/0.6.0/glonner_0.6.0_linux_amd64.tar.gz"
      sha256 "435aa720f7c4e6b8971b93491fa9677a171299ef18d9510cf9961331d5a556d3"

      def install
        bin.install "glonner"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Excoriate/glonner-cli/releases/download/0.6.0/glonner_0.6.0_linux_arm64.tar.gz"
      sha256 "c78a0bff08c65b2ba285ca09a064abcbab5d6a944dccada10d1fd5379348d28f"

      def install
        bin.install "glonner"
      end
    end
  end
end
