# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GolangCliBoilerplate < Formula
  desc "ECS Deployer is a CLI tool for deploying ECS services and tasks, plus other nice stuffs."
  homepage "https://github.com/Excoriate/golang-cli-boilerplate"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Excoriate/golang-cli-boilerplate/releases/download/v1.2.0/golang-cli-boilerplate_1.2.0_darwin_amd64.tar.gz"
      sha256 "a7ebfc39470efd769481ab1422e26d5d048d3717fa41494a018618de787bab3a"

      def install
        bin.install "golang-cli-boilerplate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Excoriate/golang-cli-boilerplate/releases/download/v1.2.0/golang-cli-boilerplate_1.2.0_darwin_arm64.tar.gz"
      sha256 "08d1ac92a79111fa87202add57d753f1fed492ab612f482c2bb328ea470902c6"

      def install
        bin.install "golang-cli-boilerplate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Excoriate/golang-cli-boilerplate/releases/download/v1.2.0/golang-cli-boilerplate_1.2.0_linux_armv6.tar.gz"
      sha256 "eb6bc1406e1d3c86de87eca1136ba7ce5c3c3f59759c0f286fa234c418042051"

      def install
        bin.install "golang-cli-boilerplate"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Excoriate/golang-cli-boilerplate/releases/download/v1.2.0/golang-cli-boilerplate_1.2.0_linux_amd64.tar.gz"
      sha256 "a9386a9fe85610b1243493cffca518617f9f05c30584af53f984dcc6a8eef1fa"

      def install
        bin.install "golang-cli-boilerplate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Excoriate/golang-cli-boilerplate/releases/download/v1.2.0/golang-cli-boilerplate_1.2.0_linux_arm64.tar.gz"
      sha256 "5c1a4e0dc5623feea1074da49c96ef3b54b0d283ea810a69a1ff6a186cbdb6f1"

      def install
        bin.install "golang-cli-boilerplate"
      end
    end
  end
end
