# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stiletto < Formula
  desc "A CLI tool, framework, portable pipeline... anything you want it to be, for automating stuffs."
  homepage "https://github.com/Excoriate/stiletto"
  version "0.2.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Excoriate/stiletto/releases/download/v0.2.6/stiletto_0.2.6_darwin_amd64.tar.gz"
      sha256 "a3aaf4b53fdbb2ae93aff5789875a9c0b08d846b5e398e6ba48a12e7aa4a46f7"

      def install
        bin.install "stiletto"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Excoriate/stiletto/releases/download/v0.2.6/stiletto_0.2.6_darwin_arm64.tar.gz"
      sha256 "cb69a56bf46e7713953fb12be65a4baaa41366366653464217901cbfd475da2b"

      def install
        bin.install "stiletto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Excoriate/stiletto/releases/download/v0.2.6/stiletto_0.2.6_linux_arm64.tar.gz"
      sha256 "387520cb25b41874000431610d3a88b69925759a956f8e149c9a3e4c438e048b"

      def install
        bin.install "stiletto"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Excoriate/stiletto/releases/download/v0.2.6/stiletto_0.2.6_linux_armv6.tar.gz"
      sha256 "3e52ad769b3eff4acd4ebf779c695fa2391febc610abfefd0f075030a5cdebed"

      def install
        bin.install "stiletto"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Excoriate/stiletto/releases/download/v0.2.6/stiletto_0.2.6_linux_amd64.tar.gz"
      sha256 "154483f714a02e210859071141f8fa87452cbc07ea4ed9c0ef3ef073c8a48684"

      def install
        bin.install "stiletto"
      end
    end
  end
end
