# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stiletto < Formula
  desc "A CLI tool, framework, portable pipeline... anything you want it to be, for automating stuffs."
  homepage "https://github.com/Excoriate/stiletto"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Excoriate/stiletto/releases/download/v0.0.2/stiletto_0.0.2_darwin_amd64.tar.gz"
      sha256 "1e878a9d98d9ce6936c3c5f751fc2e926f1612c590ec62f1ae2e7269fa9e66b9"

      def install
        bin.install "stiletto"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Excoriate/stiletto/releases/download/v0.0.2/stiletto_0.0.2_darwin_arm64.tar.gz"
      sha256 "426e43e0d829c6f5cb11bb5b1e0cba82d53ee3deb74deadf552bbeb7065ab754"

      def install
        bin.install "stiletto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Excoriate/stiletto/releases/download/v0.0.2/stiletto_0.0.2_linux_armv6.tar.gz"
      sha256 "c36e98bf9147c93083314b73560518183d68e05ba0ae11df227c31ddcda2f317"

      def install
        bin.install "stiletto"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Excoriate/stiletto/releases/download/v0.0.2/stiletto_0.0.2_linux_amd64.tar.gz"
      sha256 "fde6d108488771e7a64837bd99a29c48b6a5727e42391247abbc5f96f557bcc1"

      def install
        bin.install "stiletto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Excoriate/stiletto/releases/download/v0.0.2/stiletto_0.0.2_linux_arm64.tar.gz"
      sha256 "99b46b2593379887d1618870b4643139c942f7f5ae09de59fc89bd9764daa37c"

      def install
        bin.install "stiletto"
      end
    end
  end
end
